optimize sonar method and judge response code
alauda/bergamot pull request #4
Opened 2018-05-16 04:56 UTC by adolphlwq

2018-05-21 07:35 UTC, adolphlwq commented
@chengjingtao 更新，使用gorequest自带的retry机制，支持根据response的code判断是否retry，详情见https://github.com/parnurzeal/gorequest/blob/master/gorequest.go#L253

2018-05-22 05:45 UTC, chengjingtao requested changes

2018-05-22 05:45 UTC, chengjingtao commented on sonarqube/sonarqube.go
> +		httpClient.Logger.Errorf("request error after %d times, error is: %v",
把  request的路径信息打印出来

2018-05-22 05:45 UTC, chengjingtao commented on sonarqube/sonarqube.go
> +		err := fmt.Errorf("parse response body error, body is %s, error is %v",
错误信息写错了，这里是状态码不对。另外， response body 内容 会很多。不要把日志和 返回的error等同。上次已经说过了。
另外 error is %v 里边 err 是nil.
可以 日志里打印全部信息。 error 里边，就不需要 body 了, 但需要有  statusCode

2018-05-22 05:45 UTC, chengjingtao commented on sonarqube/sonarqube.go
> +		return fmt.Errorf("bad request, response code is %d, body is %s", resp.StatusCode, body)
log不要当error 用。

2018-05-22 05:45 UTC, chengjingtao commented on sonarqube/sonarqube.go
> +		resp, body, errs = httpClient.superAgent.
retry的逻辑有些简单暴力。可以看下原来的http client  的retry 时机。

2018-05-22 05:45 UTC, chengjingtao commented on sonarqube/sonarqube.go
> +			return "", fmt.Errorf("parse response body error, response code is %d, body is %s, error is %v",
同样的问题。

2018-05-22 05:45 UTC, chengjingtao commented on sonarqube/sonarqube.go
>  	if sonar.Version != SONAR_VERSION_64 {
这个不是跟我们 讨论的 razzil的 一样么，处理 多版本的问题。这么搞， 以后兼容其他版本，都在这里加  if else么？

2018-05-22 05:45 UTC, chengjingtao commented on sonarqube/sonarqube.go
> +		err = fmt.Errorf("ServerError5xx, response code is %d, response body is: %s", statusCode, data)
同

2018-05-22 08:28 UTC, adolphlwq commented on sonarqube/sonarqube.go
> +		err = fmt.Errorf("ServerError5xx, response code is %d, response body is: %s", statusCode, data)
已改

2018-05-22 08:28 UTC, adolphlwq commented on sonarqube/sonarqube.go
> +		err = fmt.Errorf("ServerError5xx, response code is %d, response body is: %s", statusCode, data)
已改

2018-05-22 08:29 UTC, adolphlwq commented on sonarqube/sonarqube.go
>  	if sonar.Version != SONAR_VERSION_64 {
因为目前只有6.0.0和6.4.0两个版本，所以用这种写法，已经换成swtich了

2018-05-22 08:29 UTC, adolphlwq commented on sonarqube/sonarqube.go
> +		err := fmt.Errorf("parse response body error, body is %s, error is %v",
嗯，这里已经改了

2018-05-22 08:29 UTC, adolphlwq commented on sonarqube/sonarqube.go
> +		httpClient.Logger.Errorf("request error after %d times, error is: %v",
加了

2018-05-22 08:31 UTC, danielfbm commented on sonarqube/sonarqube.go
> +	}
```
if logger == nil {
   logger = GetDefaultLogger("[alauda-sonarqube]")
}
sonar.Logger = logger
```
?

2018-05-22 08:31 UTC, danielfbm commented on sonarqube/sonarqube.go
> +	codes      []int
`code` 需要更明确，只看codes这个字段不知道它最终用处是什么

2018-05-22 08:31 UTC, danielfbm commented on sonarqube/logger.go
> +}
为什么添加了 logrus的依赖？bergamot本身有自己的logger，那么对bergamot的用户来说要么提供一些logger setter的方案并且让用户选择要使用什么logger

2018-05-22 08:31 UTC, danielfbm commented on sonarqube/sonarqube.go
> +	codes      []int
用 errorCodes如何？

2018-05-22 08:33 UTC, adolphlwq commented on sonarqube/sonarqube.go
> +	}
好

2018-05-22 08:35 UTC, adolphlwq commented on sonarqube/sonarqube.go
> +	codes      []int
这里已经更新过了吧，用retryStatusCodes了

2018-05-23 07:21 UTC, chengjingtao approved these changes

2018-05-23 07:21 UTC, chengjingtao commented on sonarqube/sonarqube.go
> +		sonar.Logger.Debugf("not expected response, code is %d, body is %s", resp.StatusCode, body)
应该用error, 其他对应看下。

2018-05-23 07:23 UTC, chengjingtao commented
该用 error 级别 的用error级别，修下这个，其他没啥问题了。
合并时  squash 一下。

2018-05-23 07:35 UTC, merged